[TTmTDBde430]
git-tree-sha1 = "de3fba2237359dc941a057d492c305afeccba133"
lazy = true

    [[TTmTDBde430.download]]
    sha256 = "a8e09c3d2f68f77c641eed0b41d2441b11a7b4f12daed8144638fdca02eb4d5d"
    url = "https://ssd.jpl.nasa.gov/ftp/eph/planets/bsp/TTmTDB.de430.19feb2015.bsp"

[a99942]
git-tree-sha1 = "7cdf1265a22c52329651c4a71a9835d1b90f568e"
lazy = true

    [[a99942.download]]
    sha256 = "d1cdcad22c8060e98d7ca116973b64bc65cdb5e62fb045637701b57aa146a434"
    url = "https://raw.githubusercontent.com/PerezHz/jpleph/main/a99942.tar.gz"

[de430]
git-tree-sha1 = "db3e3a765712a792a7f4a73634213d53fc0561ec"
lazy = true

    [[de430.download]]
    sha256 = "b70b72fde86923475fac6cec1e0887040bb80ffe159f153aab647cdfdf897351"
    url = "https://ssd.jpl.nasa.gov/ftp/eph/planets/bsp/de430_1850-2150.bsp"

[debias]
git-tree-sha1 = "cfd0d2615770087d3c564b7f6143f01930ccb45e"
lazy = true

    [[debias.download]]
    sha256 = "8b107db9506ec45c8cad78d0981c48693c6e5957912df95f4a3df826c7736227"
    url = "https://ssd.jpl.nasa.gov/ftp/ssd/debias/debias.tgz"

[debias_2014]
git-tree-sha1 = "1b6a82575ac74386b893f8c51361d19d350bd234"
lazy = true

    [[debias_2014.download]]
    sha256 = "1d44c6443d08f83c79017afd218c3b4e326c573d84842c88713e4b6c8d6d5b03"
    url = "https://ssd.jpl.nasa.gov/ftp/ssd/debias/debias_2014.tgz"

[debias_2018]
git-tree-sha1 = "ea7915a243ea4c8e0960817f50677598076beeaa"
lazy = true

    [[debias_2018.download]]
    sha256 = "288132cefea7f1bdf0989782db1173948dd7dfef7da31910be90b16b73cfea6c"
    url = "https://ssd.jpl.nasa.gov/ftp/ssd/debias/debias_2018.tgz"

[debias_hires2018]
git-tree-sha1 = "cebf83360f68870a628805aea9b4261d0d6b4545"
lazy = true

    [[debias_hires2018.download]]
    sha256 = "2b292fc79c202d38dfab386783fee10d422f6919afc58348c72059710dd6cd92"
    url = "https://ssd.jpl.nasa.gov/ftp/ssd/debias/debias_hires2018.tgz"

[naif0012]
git-tree-sha1 = "8fa307fe9da2a63ed0cf9d681540d94a619a0995"
lazy = true

    [[naif0012.download]]
    sha256 = "678e32bdb5a744117a467cd9601cd6b373f0e9bc9bbde1371d5eee39600a039b"
    url = "https://naif.jpl.nasa.gov/pub/naif/generic_kernels/lsk/naif0012.tls"

[sseph_p100]
git-tree-sha1 = "d4d91f0045063719c9bf581bf20bbc212327b2d0"
lazy = true

    [[sseph_p100.download]]
    sha256 = "25b525ffef5c05cc51ee554760ae83107b9bd163577439470b60c2d4c7153a21"
    url = "https://github.com/LuEdRaMo/sseph/raw/main/sseph343ast016_p100y_et.tar.gz"
