name = "NEOs"
uuid = "b41c07a2-2abb-11e9-070a-c3c1b239e7df"
authors = ["Jorge A. Pérez Hernández", "Luis Benet", "Luis Eduardo Ramírez Montoya"]
version = "0.6.2"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
EarthOrientation = "732a3c5d-d6c0-58bc-adb1-1b51709a25e2"
HORIZONS = "5a3ac768-beb4-554a-9c98-3342fe3377f5"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Healpix = "9f4e344d-96bc-545a-84a3-ae6b9e1b672b"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
IntervalRootFinding = "d2bf35a9-74e0-55ec-b149-d360ff49b807"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PlanetaryEphemeris = "d83715d0-7e5f-11e9-1a59-4137b20d8363"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
RemoteFiles = "cbe49d4c-5af1-5b60-bb70-0a60aa018e1b"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SPICE = "5bab7191-041a-5c2e-a744-024b9c3a5062"
SatelliteToolbox = "6ac157d9-b43d-51bb-8fab-48bf53814f4a"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TaylorIntegration = "92b13dbe-c966-51a2-8445-caca9f8a7d42"
TaylorSeries = "6aa5eb33-94cf-58f4-a9d0-e4b2c4fc25ea"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[weakdeps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[extensions]
DataFramesExt = ["DataFrames", "Tables"]

[compat]
AutoHashEquals = "0.2"
DataFrames = "1.5"
DelimitedFiles = "1"
EarthOrientation = "0.7"
HORIZONS = "0.3"
HTTP = "1.9.5"
Healpix = "4"
IntervalArithmetic = "0.20"
IntervalRootFinding = "0.5.11"
JLD2 = "0.4"
PlanetaryEphemeris = "0.6"
Quadmath = "0.5"
Requires = "0.5.2, 1"
SPICE = "0.2"
SatelliteToolbox = "0.10"
StatsBase = "0.33, 0.34"
Tables = "1.10"
TaylorIntegration = "0.13"
TaylorSeries = "0.15"
julia = "1.6"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
